### ISSUE TITLE
Youtube on Firefox-esr no  Hdmi sound 

### ISSUE THREAD

**Issue by mikefeign** [TerraGitHuB/gnomeforpi#12]
Hi, 
Thank for the script, I cam login to Gnome on Xorg now but I have an issue with the sound. I am using monitor speaker via Hdmi but when I play Youtube on Firefox, there's no sound. If I use Chromium, I have the sound. 

Hope you can recommend something.

Thanks

**Comment by TheMaroonHatHacker** [comment]
Does audio work from the other audio outputs (headphone jack, bluetooth) in firefox?

**Comment by mikefeign** [comment]
No, I tried to connect to a Bluetooth speaker but no sound either. It's wired.

**Comment by TheMaroonHatHacker** [comment]
The fact that chromium works probably means it's firefox's fault. I'll take a look at somepoint, but can't at the moment as I'm currently away from home with no Raspberry Pi at hand.

**Comment by mikefeign** [comment]
That's OK. I think it's Fireforx-esr because for some Youtube videos, it has sound and for some it doesn't have. I will just use Chromium. Thanks.

**Comment by mikefeign** [comment]
I found the solution from this link: https://www.raspberrypi.org/forums/viewtopic.php?t=185736,

I set this command: 
amixer cset numid=3 2

Now it works fine. Thanks

**Comment by TheMaroonHatHacker** [comment]
Great, I hate to ask this from you, but do you think you could replicate this with a brand new build?

It might be good to add this to the script to fix this problem (a lot of people like using firefox, so it may be good to fix that)

**Comment by mikefeign** [comment]
I am more than happy to help. Now I already switch to Pi os 64 bit, using the same script. Surprisingly Gnome software is also work. I would recommend people to test out Pi OS lite 64bit at http://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/

**Comment by TheMaroonHatHacker** [comment]
You may notice that extensions break under 64Bit. Not sure why. I'll take a look, especially since more and more people migrating to 64Bit. Glad that GNOME software works though.
