### ISSUE TITLE
How did you make the pre-built image?

### ISSUE THREAD

**Issue by danielquinn** [TerraGitHuB/gnomeforpi#14]
I'm working on a Big Project which I hope to be able distribute as a Raspberry Pi image file.  It depends on GNOME, which is how I found this repo, but I've yet to find any reasonable tutorials on how to create a Pi image.  As I see you've done just that, can I ask how?  Ideally I'm looking for a way to automate the process so I can make it part of my CI run.

**Comment by TheMaroonHatHacker** [comment]
What I did was run a brand new image of Raspberry Pi OS lite in botspot's pi power tools, then run the script making sure that the filesystem resizing wouldn't start whilst running in pi power tools. I then tried shrinking the image to as small as possible. 

I don't think you can automate the process unfortunately. I do admit my way was a little convoluted.

**Comment by danielquinn** [comment]
Hmm.  Alright then, I guess I'll stick to trying out pi-gen and see how that goes.  Thanks!

**Comment by TheMaroonHatHacker** [comment]
Good luck with your project, and sorry I couldn't help more
