### ISSUE TITLE
Extreme slowdown / freezes once login is attempted

### ISSUE THREAD

**Issue by ConnorXcrash** [TerraGitHuB/gnomeforpi#16]
I don't know if it's because of the Pi I have or what, but every time I attempt to log in, it just freezes or crashes after I enter my password. I have the Raspberry Pi 3 Model A+ by the way.

**Comment by TheMaroonHatHacker** [comment]
Interesting. 

It could be to do with the 3A+ low amount of RAM (512MB I believe) On my Pi 4B 4GB I use up about that amount of RAM easily. 

That would be my guess.

See if you can setup zram in the command line. Guide here: https://github.com/novaspirit/rpi_zram Maybe that might help performance issues.
