### ISSUE TITLE
Boot hangs on starting power management daemon

### ISSUE THREAD

**Issue by derekscha** [TerraGitHuB/gnomeforpi#20]
Fresh installation of Raspbian Lite, x64 bit (bullseye; re: 2022-09-22) on a Raspberry Pi 4B.  Running the script then rebooting results in the boot process hanging at attempting to start the Power Management daemon.

**Comment by ghost** [comment]
Hmmm... Just out of interest, do you have another SD card to check with? 
I'm not 100% sure what's happening here, and what the script would've done to cause this.

Just as another thing you can check, I'll link a zip with a version before the most recent merge. See if that causes the same behaviour. Unfortunately, I'm quite busy, so finding time to test this kind of thing is challenging.
