### ISSUE TITLE
VNC server hangs on connecting...

### ISSUE THREAD

**Issue by Babyyoda777** [TerraGitHuB/gnomeforpi#21]
Was working with same install of latest raspberry pi os, but even after enabling VNC again and rebooting the pi, the vnc connection no longer works although ssh works fine.

**Comment by zxdavb** [comment]
Just checking - do you still have HDMI connected? A simple test is to check VNC (or RDP) with/without HDMI attached.

If not, if you want headless, use a HDMI emulator/dummy plus.
