### ISSUE TITLE
Gnome wayland incompatible with firefox ESR, chromium browser windows on RP4.

### ISSUE THREAD

**Issue by betrixed** [TerraGitHuB/gnomeforpi#22]
Situation on Raspberry pi 4, 8GB, dual monitors, selected GDM3 for login.  After login to gnome wayland, which was default after script install, both firefox ESR and chromium display  nonsense crap on screen, like a misdirected bitmap blit from random memory.  Evolution client and terminal windows looked fine. Suggested Fix: Don't set default into gnome wayland, change DE to Gnome on Xorg, until whatever cause is fixed.

**Comment by TheMaroonHatHacker** [comment]
Interesting, last time I'd checked this wasn't an issue on wayland. Thanks for letting me know.

Also sorry for late response
