### ISSUE TITLE
Not expected result?  No GDM, No GNOME Desktop?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [TerraGitHuB/gnomeforpi#26]
Not expected result?  No GDM, No GNOME Desktop?  Followed documented steps, and Pi rebooted back into the original Pi OS desktop based on Pixel.  Help?  Does this not work with Pi OS based on bookworm?  If not, how about updating the documentation.

**Comment by TheMaroonHatHacker** [comment]
There is a half decent chance it doesn't, as I haven't had the chance to test this project for a long time. 

I'll probably need to redo this entire project to accommodate the new Raspberry Pi OS release(s) since the project has been up.

**Comment by Jibun-no-Kage** [comment]
Actually, I think figured out what happen... the script seem to halt... at the prompt for greeter selection.  I think my SSH session dropped out.  So I restarted the script, and it completed.  I am still testing, but so far the result seems functional.  I will post back results, once I have tested things a bit more.
