### ISSUE TITLE
space that brakes a comment

### ISSUE THREAD

**Issue by Relluem94** [TerraGitHuB/gnomeforpi#8]
Line 25 
apt-get install -y gnome gnome-shell rpi-chromium-mods xorg piwiz#installs all required packges
has to be 
apt-get install -y gnome gnome-shell rpi-chromium-mods xorg piwiz #installs all required packges

**Comment by Relluem94** [comment]
https://github.com/TerraGitHuB/gnomeforpi/pull/9

**Comment by TheMaroonHatHacker** [comment]
Fixed, thanks!
